server:
  port: 9099

logging:
  level:
    root: debug
    org.springframework: trace
    org.hibernate: trace
    org.keycloak: trace

debug: true

spring:
  application:
    name: "@pom.artifactId@"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: test
    password: test
    hikari:
      maximum-pool-size: 4

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        use_sql_comments: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        integration.envers.enabled: false
#  flyway:
#    enabled: true
#    locations: classpath:db/migration/{vendor}
#    baseline-on-migrate: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  boot:
    admin:
      client:
        enabled: false
#        service-base-url: http://storage.tpi.tssit.cn
        url: http://127.0.0.1:8980
        username: "user"       #These two are needed so that the client
        password: "password"   #can register at the protected server api
        instance:
          metadata:
            user.name: "user"         #These two are needed so that the server
            user.password: "password" #can access the protected client endpoints

keycloak:
  enabled: true
  connection-pool-size: 4
  auth-server-url: http://127.0.0.1:8080/auth
  realm: dev
  ssl-required: external
  resource: crm-demo
  credentials:
    secret: 0ebb62fc-a02e-4fdf-9f67-e5c94cba180a
  use-resource-role-mappings: true
  confidential-port: 0
  autodetect-bearer-only: true
  cors: true
  principal-attribute: preferred_username
  policy-enforcer-config:
#    user-managed-access: {}   #uma
    enforcement-mode: ENFORCING #PERMISSIVE #DISABLED #ENFORCING
#    lazy-load-paths: true
#    path-cache:
#      max-entries: 100
#      lifespan: 30000
    on-deny-redirect-to: /
  security-constraints:
    - auth-roles:
      - user
#      security-collections:
#        - name: protected
#          patterns:
#            - /*
