server:
  port: 9099

logging:
  level:
    root: info
    org.springframework.data: trace
    org.hibernate: trace

debug: true

spring:
  application:
    name: "@pom.artifactId@"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: test
    password: test

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        use_sql_comments: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
#  flyway:
#    enabled: true
#    locations: classpath:db/migration/{vendor}
#    baseline-on-migrate: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  boot:
    admin:
      client:
        enabled: false
#        service-base-url: http://storage.tpi.tssit.cn
        url: http://127.0.0.1:8980
        username: "user"       #These two are needed so that the client
        password: "password"   #can register at the protected server api
        instance:
          metadata:
            user.name: "user"         #These two are needed so that the server
            user.password: "password" #can access the protected client endpoints

